### ISSUE TITLE
Generate the code in alphabetical order

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ping-protocol#108]
I ran into an issue where the diffs when updating the generated python files is huge because things are out of order.
We should order the structures in each section (getters, setters, control, and general) alphabetically to prevent changes to the json data of affecting the generated code.
And it improves readability.

**Comment by Williangalvani** [comment]
I just checked, the behavior changes between Python3 and Ptython2. possibly [because in Python3 dicts are insertion-ordered](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)

**Comment by patrickelectric** [comment]
Yes, you can check the we generate everything with python 3. You can also specify the dict organization in python2.

**Comment by Williangalvani** [comment]
You can do it with orderedDict. But my point is that the code should behave the same way in both versions

**Comment by jaxxzer** [comment]
I agree.

My recomendation is to use `|sorted` filters in jinja or use orderedDict.

**Comment by jaxxzer** [comment]
http://jinja.pocoo.org/docs/2.10/templates/#sort

**Comment by Williangalvani** [comment]
I thought those were implemented by Django, good to know they are actually part of Jinja!
I'll test it here
