### ISSUE TITLE
Decide reserved range for device id

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-protocol#165]
All of our device id field documentation says that only 255 is reserved, except for ping360 (which says 0 + 255 are reserved): http://docs.bluerobotics.com/ping-protocol/pingmessage-ping360/

@patrickelectric do we need to reserve zero? we should update the fields to be consistent.

**Comment by patrickelectric** [comment]
The idea is to use 0 for error handle and 255 for broadcast.

**Comment by patrickelectric** [comment]
done.
