### ISSUE TITLE
Cannot connect to my ping360 device via udp port

### ISSUE THREAD

**Issue by luuckiest** [bluerobotics/ping-protocol#187]
I believe I have set up my routing correctly. 
![image](https://user-images.githubusercontent.com/21696887/122844665-23c3d800-d2d0-11eb-982c-ec86412b2026.png)
When I am simply using the port to try to initialize the device, it will always fail. No matter what I do, it won't talk via the UDP port.

Is there anything I shall try here?

**Comment by patrickelectric** [comment]
You should not route or do any configuration with the ROV, just make sure that you are running the latest version of companion and it should work. Make sure to delete the router configuration that you have created, since this will probably result in an intern conflict.

**Comment by patrickelectric** [comment]
For more information, check the product page: https://bluerobotics.com/store/sensors-sonars-cameras/sonar/ping360-sonar-r1-rp/
