### ISSUE TITLE
Add pingmessage source to version control

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-protocol#19]
Generating it as part of a build is a bad idea for a more than one reason:

The entire source code for the actual project is not visible to those who may just want to take a quick look.

Modifications to these files will be overwritten without warning, for example when trying to rework/test the implementation, I have to remember to comment out the build step where the files are overwritten.

We are adding a dependency on python just to build the project, leading to trouble on windows.

**Comment by patrickelectric** [comment]
From Mastering Git:

> a generated file should not be stored in a version control repository.

> Which types of file should be ignored?
> ...
> First, you should never track automatically generated files (usually generated by the build system of a project). If you add them to the repository, there is a high chance that they will get out of sync with their source. Besides, they are not necessary, as you can always re-generate them. The only possible exception is generated files where the source changes rarely, and generating them requires extra tools that developers might not have (if the source changes more often, you can use an orphan branch to store these generated files, and refresh this branch only at release time).
---
> Modifications to these files will be overwritten without warning, for example when trying to rework/test the implementation, I have to remember to comment out the build step where the files are overwritten.

I usually do the modifications directly in the template, modifying generated code directly is like working with svg in a text editor and not with inkscape.

> We are adding a dependency on python just to build the project, leading to trouble on windows.
Yes, besides that, the project only uses standards python projects. I don't see python as a high price, if someone want to compile and modify the software.

I believe that the best solution is to create an orphan branch updated by travis, containing the generated files.

**Comment by jaxxzer** [comment]
> The only possible exception is generated files where the source changes rarely, and generating them requires extra tools that developers might not have

this is the case for us

**Comment by patrickelectric** [comment]
Can we close this, or we are going to create a repository only for the cpp part ?

**Comment by jaxxzer** [comment]
I'm in agreement with @patrickelectric sentiments. We should make a separate repository or orphan branch for generated files.
