### ISSUE TITLE
Ping360 setters are missing

### ISSUE THREAD

**Issue by incebellipipo** [bluerobotics/ping-protocol#195]
We should be able to change rotation angle, speed, and other things, right?

Where are the definitions for those functionalities?

Documentation doesn't mention setting those other values. My take from the documentation is that `device_id` is the only thing I can change with the vehicle.

This is quite confusing and requires an immediate fix. I'm willing to work on it but I don't know the `message_id`s for those functions. I don't even know if it is implemented in firmware.

**Comment by patrickelectric** [comment]
Hi @incebellipipo,

Thanks you for your patience, the company was closed for the holidays. 
Everything that you said can be configured with the [**transducer** message](https://docs.bluerobotics.com/ping-protocol/pingmessage-ping360/#2601-transducer).
Let me know if you have any further questions.
